package BimBamBouML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Duration extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Duration() {
    super(0x9cde07181d5f461dL, 0xaed55578dacf102eL, 0x120425afff1eb4bfL, "Duration", "r:d77e8a00-b786-477d-87ac-e13b035d3730(BimBamBouML.structure)/1298204030419252415");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_NOTE_0 = new EnumerationDescriptor.MemberDescriptor("NOTE", "Note", 0x120425afff1eb4c0L, "r:d77e8a00-b786-477d-87ac-e13b035d3730(BimBamBouML.structure)/1298204030419252416");
  private final EnumerationDescriptor.MemberDescriptor myMember_HALF_NOTE_0 = new EnumerationDescriptor.MemberDescriptor("HALF_NOTE", "Half Note", 0x120425afff1eb4c1L, "r:d77e8a00-b786-477d-87ac-e13b035d3730(BimBamBouML.structure)/1298204030419252417");
  private final EnumerationDescriptor.MemberDescriptor myMember_QUARTER_NOTE_0 = new EnumerationDescriptor.MemberDescriptor("QUARTER_NOTE", "Quarter Note", 0x120425afff1eb4c4L, "r:d77e8a00-b786-477d-87ac-e13b035d3730(BimBamBouML.structure)/1298204030419252420");
  private final EnumerationDescriptor.MemberDescriptor myMember_EIGHTH_NOTE_0 = new EnumerationDescriptor.MemberDescriptor("EIGHTH_NOTE", "Eighth Note", 0x120425afff1eb4c8L, "r:d77e8a00-b786-477d-87ac-e13b035d3730(BimBamBouML.structure)/1298204030419252424");
  private final EnumerationDescriptor.MemberDescriptor myMember_SIXTEENTH_NOTE_0 = new EnumerationDescriptor.MemberDescriptor("SIXTEENTH_NOTE", "Sixteenth Note", 0x120425afff1eb4cdL, "r:d77e8a00-b786-477d-87ac-e13b035d3730(BimBamBouML.structure)/1298204030419252429");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x9cde07181d5f461dL, 0xaed55578dacf102eL, 0x120425afff1eb4bfL, 0x120425afff1eb4c0L, 0x120425afff1eb4c1L, 0x120425afff1eb4c4L, 0x120425afff1eb4c8L, 0x120425afff1eb4cdL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_NOTE_0, myMember_HALF_NOTE_0, myMember_QUARTER_NOTE_0, myMember_EIGHTH_NOTE_0, myMember_SIXTEENTH_NOTE_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "NOTE":
        return myMember_NOTE_0;
      case "HALF_NOTE":
        return myMember_HALF_NOTE_0;
      case "QUARTER_NOTE":
        return myMember_QUARTER_NOTE_0;
      case "EIGHTH_NOTE":
        return myMember_EIGHTH_NOTE_0;
      case "SIXTEENTH_NOTE":
        return myMember_SIXTEENTH_NOTE_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
