package BimBamBouML.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class Note_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.tone$Wyyw) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x9cde07181d5f461dL, 0xaed55578dacf102eL, 0x120425afff1eb4d3L, "BimBamBouML.structure.Tone"), 0x120425afff1eb4d5L, "BASS_DRUMS")) {
      tgs.append("O ");
    }
    if (SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.tone$Wyyw) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x9cde07181d5f461dL, 0xaed55578dacf102eL, 0x120425afff1eb4d3L, "BimBamBouML.structure.Tone"), 0x120425afff209233L, "CRASH_CYMBAL")) {
      tgs.append("* ");
    }
    if (SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.tone$Wyyw) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x9cde07181d5f461dL, 0xaed55578dacf102eL, 0x120425afff1eb4d3L, "BimBamBouML.structure.Tone"), 0x2d65836978199e41L, "HI_HAT")) {
      tgs.append("^ ");
    }
    if (SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.tone$Wyyw) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x9cde07181d5f461dL, 0xaed55578dacf102eL, 0x120425afff1eb4d3L, "BimBamBouML.structure.Tone"), 0x2d65836978198900L, "SNARE_DRUM")) {
      tgs.append("S ");
    }
    if (SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.tone$Wyyw) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x9cde07181d5f461dL, 0xaed55578dacf102eL, 0x120425afff1eb4d3L, "BimBamBouML.structure.Tone"), 0x2d65836978199e39L, "RIDE_CYMBAL")) {
      tgs.append("~ ");
    }
    if (SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.tone$Wyyw) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x9cde07181d5f461dL, 0xaed55578dacf102eL, 0x120425afff1eb4d3L, "BimBamBouML.structure.Tone"), 0x120425afff1eb4d8L, "KICKS")) {
      tgs.append("X ");
    }
    if (SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.tone$Wyyw) == SEnumOperations.getMember(MetaAdapterFactory.getEnumeration(0x9cde07181d5f461dL, 0xaed55578dacf102eL, 0x120425afff1eb4d3L, "BimBamBouML.structure.Tone"), 0x120425afff209b37L, "SILENCE")) {
      tgs.append("$ ");
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty tone$Wyyw = MetaAdapterFactory.getProperty(0x9cde07181d5f461dL, 0xaed55578dacf102eL, 0x120425afff1eb4baL, 0x120425afff1eb4dcL, "tone");
  }
}
