package BimBamBouML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int ChordNote = 0;
  public static final int Mapping = 1;
  public static final int Note = 2;
  public static final int NoteConfig = 3;
  public static final int Pattern = 4;
  public static final int Song = 5;
  public static final int Sound = 6;
  public static final int ToneNote = 7;
  public static final int Track = 8;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x9cde07181d5f461dL, 0xaed55578dacf102eL);
    builder.put(0x21168ba47fd8fd65L, ChordNote);
    builder.put(0x21168ba47fd6bfbcL, Mapping);
    builder.put(0x21168ba47fd8fd6aL, Note);
    builder.put(0x21168ba47fd6bfb9L, NoteConfig);
    builder.put(0x120425afff1eb4aeL, Pattern);
    builder.put(0x73c098f5eaa10f88L, Song);
    builder.put(0x120425afff1eb4b3L, Sound);
    builder.put(0x120425afff1eb4baL, ToneNote);
    builder.put(0x120425afff1eb4a9L, Track);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
