package BimBamBouML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Note = 0;
  public static final int Pattern = 1;
  public static final int Sound = 2;
  public static final int Track = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x9cde07181d5f461dL, 0xaed55578dacf102eL);
    builder.put(0x120425afff1eb4baL, Note);
    builder.put(0x120425afff1eb4aeL, Pattern);
    builder.put(0x120425afff1eb4b3L, Sound);
    builder.put(0x120425afff1eb4a9L, Track);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
